//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanford_EntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eNewsEntities : DbContext
    {
        public eNewsEntities()
            : base("name=eNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<stanfArticle> stanfArticles { get; set; }
        public DbSet<stanfCategory> stanfCategories { get; set; }
        public DbSet<stanfType> stanfTypes { get; set; }
        public DbSet<stanfUser> stanfUsers { get; set; }
    }
}
