//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanford_WorkingwithRazor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stanfCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stanfCategory()
        {
            this.stanfArticles = new HashSet<stanfArticle>();
        }
    
        public int Id { get; set; }

        [Display(Name="Chủ đề")]
        [Required(ErrorMessage="Bạn cần phải nhập tên chủ đề")]
        [StringLength(250, MinimumLength=5, ErrorMessage="Bạn cần phải nhập tối thiểu {1} kí tự")]
        public string CategoryName { get; set; }

        [Display(Name = "Mô tả")]
        public string CategoryDescription { get; set; }
        public string CategoryImageName { get; set; }
        public Nullable<int> NumberOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stanfArticle> stanfArticles { get; set; }
    }
}
