//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanford_EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanfType
    {
        public stanfType()
        {
            this.stanfArticles = new HashSet<stanfArticle>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string TypeDescription { get; set; }
        public Nullable<int> NumberOrder { get; set; }
    
        public virtual ICollection<stanfArticle> stanfArticles { get; set; }
    }
}
