//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanford_EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class stanfCategory
    {
        public stanfCategory()
        {
            this.stanfArticles = new HashSet<stanfArticle>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage="Bạn cần nhập tiêu đề trước khi thực hiện")]
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryImageName { get; set; }
        public Nullable<int> NumberOrder { get; set; }
    
        public virtual ICollection<stanfArticle> stanfArticles { get; set; }
    }
}
